services:
  api:
    build: .
    ports:
      - "7224:7224"
    environment:
      - ASPNETCORE_URLS=http://+:7224
      - DefaultConnectionPublish=Host=db;Port=5432;Database=SchulfunkDb;Username=schulfunk_admin;Password=DeinSicheresPasswort;
    depends_on:
      - db
    volumes:
      - ./uploads:/app/wwwroot/uploads

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=SchulfunkDb
      - POSTGRES_USER=schulfunk_admin
      - POSTGRES_PASSWORD=DeinSicheresPasswort
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
