// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurveyService.Database;

#nullable disable

namespace SurveyService.Database.migration
{
    [DbContext(typeof(SurveyContext))]
    partial class SurveyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("SurveyService.Data.AnswerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfSelectedAnswer")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuestionModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionModelId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("SurveyService.Data.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SurveyModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SurveyModelId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("SurveyService.Data.SurveyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Classes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("OnlineUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("UserIDs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Survey");
                });

            modelBuilder.Entity("SurveyService.Data.AnswerModel", b =>
                {
                    b.HasOne("SurveyService.Data.QuestionModel", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionModelId");
                });

            modelBuilder.Entity("SurveyService.Data.QuestionModel", b =>
                {
                    b.HasOne("SurveyService.Data.SurveyModel", null)
                        .WithMany("Questions")
                        .HasForeignKey("SurveyModelId");
                });

            modelBuilder.Entity("SurveyService.Data.QuestionModel", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("SurveyService.Data.SurveyModel", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
