syntax = "proto3";

option csharp_namespace = "Contracts.Protos";

package news;

import "google/protobuf/timestamp.proto"; 

message NewsMessage {
  int32 id = 1;
  string titel = 2;         
  string tag = 3;           
  string preview_text = 4;
  string main_text = 5;
  bytes image = 6;          
  google.protobuf.Timestamp created_at = 7; 
  int32 created_user_id = 8;
  string createdEmail = 9;
}

service News{
	rpc GetNewsById(GetNewsByIdRequest) returns (GetNewsByIdResponse);
	rpc GetAllNews(GetAllNewsRequest) returns (GetAllNewsResponse);
	rpc CreateNews(CreateNewsRequest) returns (CreateNewsResponse);
	rpc UpdateNews(UpdateNewsRequest) returns (UpdateNewsResponse);
	rpc DeleteNews(DeleteNewsRequest) returns (DeleteNewsResponse);
}

// Get News by id message
message GetNewsByIdRequest{
	int32 Id = 1;
}

message GetNewsByIdResponse{
	NewsMessage News = 1;
}

// Get All News message
message GetAllNewsRequest{}

message GetAllNewsResponse{
	repeated NewsMessage News = 1;
}

// Create News message
message CreateNewsRequest{
	NewsMessage News = 1;
}

message CreateNewsResponse{
	bool Success = 1;
}

// Update News message
message UpdateNewsRequest{
	NewsMessage News = 1;
}
message UpdateNewsResponse{
	bool Success = 1;
}

// Delete News message
message DeleteNewsRequest{
	int32 Id = 1;
}
message DeleteNewsResponse{
	bool Success = 1;
}