syntax = "proto3";

option csharp_namespace = "Contracts.Protos";
package survey;

import "google/protobuf/timestamp.proto"; 


message AnswerMessage {
	string options = 1;
	int32 number_of_selected_answer = 2;
}

message QuestionMessage {
	string question = 1;
	repeated AnswerMessage options = 2;
}

message SurveyMessage {
	int32 id = 1; 
	string title = 2;
	int32 group_id = 3;
	repeated string classes = 4;

	google.protobuf.Timestamp created_at = 5;
	google.protobuf.Timestamp online_until = 6;
	
	repeated int32 user_i_ds = 7; 
	repeated QuestionMessage questions = 8;
}


service Survey {
	rpc GetAllSurveys(GetAllSurveysRequest) returns (GetAllSurveysResponse);
	rpc CreateSurvey(CreateSurveyRequest) returns (CreateSurveyResponse);
	rpc UpdateSurveyAnswer(UpdateSurveyAnswerRequest) returns (UpdateSurveyAnswerResponse);
	rpc DeleteSurvey(DeleteSurveyRequest) returns (DeleteSurveyResponse);
}

message GetAllSurveysRequest{}
message GetAllSurveysResponse{
	repeated SurveyMessage Surveys = 1;
}

message CreateSurveyRequest{
	SurveyMessage Survey = 1;
}
message CreateSurveyResponse{
	bool Success = 1;
}

message UpdateSurveyAnswerRequest{
	int32 userId = 1;
	int32 answerId = 2;
}
message UpdateSurveyAnswerResponse{
	bool Success = 1;
}

message DeleteSurveyRequest{
	int32 Id = 1;
}
message DeleteSurveyResponse{
	bool Success = 1;
}