syntax = "proto3";

option csharp_namespace = "Contracts.Protos";

package user;

enum UserGroup{
	STUDENT = 0;
    TEACHER = 1;
    ADMIN = 2;
    STUDENT_REPRESENTATIVES = 3;
    CLASS_REPRESENTATIVES = 4;
}

message ClassMessage{
	string Name = 1;
}

message UserMessage{
	string Name = 1;
	string Lastname = 2;
	string Email = 3;
	string Password = 4;
	ClassMessage Class = 5;
	UserGroup Group = 6;
}

message LoginMessageResponse{
	string Name =1;
	string Lastname = 2;
	string Email = 3;
	ClassMessage Class = 4;
	UserGroup Group = 5;
}

service User{
	rpc Login(LoginRequest) returns (LoginResponse);
	rpc GetUserByEmail(GetUserByEmailRequest) returns (GetUserByEmailResponse);
	rpc GetAllUsers(GetAllUsersRequest) returns (GetAllUsersResponse);
	rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);
	rpc UpdateUser(UpdateUserRequest) returns (UpdateUserResponse);
	rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse);
	rpc GetAllClasses(GetAllClassesRequest) returns (GetAllClassesResponse);
	rpc CreateClass (CreateClassRequest) returns (CreateClassResponse);
}

// Get User by password and email message
message LoginRequest{
	string Email = 1;
	string Password = 2;
}

message LoginResponse{
	LoginMessageResponse User = 1;
}

// Create Users message
message GetAllUsersRequest{}

message GetAllUsersResponse{
	repeated UserMessage Users = 1;
}


message GetUserByEmailRequest{
	string email = 1;
}
message GetUserByEmailResponse{
	 UserMessage User = 1;
	 int32 userId = 2;
}

// Create User message
message CreateUserRequest{
	UserMessage User = 1;
}

message CreateUserResponse{
	bool Success = 1;
}

// Update User message
message UpdateUserRequest{
	UserMessage User = 1;
}
message UpdateUserResponse{
	bool Success = 1;
}

// Delete User message
message DeleteUserRequest{
	string Email = 1;
}
message DeleteUserResponse{
	bool Success = 1;
}

//Get ALl Classes message
message GetAllClassesRequest{}

message GetAllClassesResponse{
	repeated ClassMessage Classes = 1;
}

// Create Class message
message CreateClassRequest{
	ClassMessage Class = 1;
}
message CreateClassResponse{
	bool Success = 1;
}